### ISSUE TITLE
QuitRoot button non-functional

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#105]
in the REve browser display, the 'QuitRoot' button seems to do nothing.  No response is reported on the server side, and there's no change in the display.  The only way I can find to disconnect is to close the browser tab.  That is registered at the server as 'connection lost'.

**Comment by sophiemiddleton** [comment]
Yes, this is something which seems to occur in remote mode. The code it calls is here: https://github.com/Mu2e/REve/blob/main/src/EventDisplayManager.cc#L22 it should kill the thread, I think this doesnt work any longer but it used to. Perhaps this is due to remote view .v. local view, or something changed in ROOT

**Comment by sophiemiddleton** [comment]
Essentially it does the same thing as "next event" (which it now still does) but was meant to throw an error which would then kill the process. It needs rethinking...
